### ISSUE TITLE
where are circuit netlist？

### ISSUE THREAD

**Issue by ElevenMorning** [AvestimehrResearchGroup/AICircuit#1]
Nice dataset，but where are circuit netlist i can run？

**Comment by AsalMehradfar** [comment]
Thank you for your interest! I have included the ocean script files in the repository (Simulation/Ocean), which should help you run the simulations. Please feel free to check them out and let me know if they meet your needs or if you're specifically looking for the netlist files. I'd be happy to assist further!

**Comment by z24tao** [comment]
The ocean files seem to only include run scripts, but what we require is the transistor level netlist in order to actually run the simulation, are those available? Also do you happen to have a discord server or something for communication? Thanks!

**Comment by AsalMehradfar** [comment]
I've added the transistor-level netlists to the repository. You can find them in the Simulation/Netlists directory.

As for communication, we don't have a Discord server at the moment, but feel free to ask any questions in the Discussions section of the repository, or you can contact me directly via email.

Also, let me know if you need anything else!
